import {
  CalendarDaysIcon,
  CheckCircle2Icon,
  CircleAlertIcon,
  CircleQuestionMarkIcon,
  EyeIcon,
  EyeOffIcon,
  HeartIcon,
  HouseIcon,
  InfoIcon,
  LoaderCircleIcon,
  LogOutIcon,
  MessagesSquareIcon,
  SearchIcon,
  SettingsIcon,
  TriangleAlertIcon,
  UserIcon,
  WalletIcon,
  XIcon,
  ZapIcon,
} from 'lucide-angular';

export const icons = {
  home: HouseIcon,
  calendarDays: CalendarDaysIcon,
  heart: HeartIcon,
  messages: MessagesSquareIcon,
  search: SearchIcon,
  wallet: WalletIcon,
  settings: SettingsIcon,
  user: UserIcon,
  help: CircleQuestionMarkIcon,
  logOut: LogOutIcon,
  zap: ZapIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  info: InfoIcon,
  checkCircle: CheckCircle2Icon,
  circleAlert: CircleAlertIcon,
  triangleAlert: TriangleAlertIcon,
  close: XIcon,
  loaderCircle: LoaderCircleIcon,
};
